version: '3'

services:
  db:
    build: ./db
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
